import CaseIntroSection from '../sections/CaseIntroSection';
import CaseZigzagChapterSection from '../sections/CaseZigzagChapterSection';
import CaseKeyLearningsSection from '../sections/CaseKeyLearningsSection';
import CaseCtaSection from '../sections/CaseCtaSection';
import { INTRO_STACK_LAYOUTS, ZIGZAG_STACK_LAYOUTS } from '../mediaStackLayouts';
import {
  DEMO_INTRO,
  DEMO_INTRO_ASIDE,
  DEMO_INTRO_HERO_SPLIT,
  DEMO_ZIGZAG,
  DEMO_ZIGZAG_FLIP,
  DEMO_ZIGZAG_SHIFT,
  DEMO_ZIGZAG_BODY_PROOFS,
  DEMO_ZIGZAG_BODY_AWARDS,
  DEMO_ZIGZAG_SPLIT_PROSE,
  DEMO_ZIGZAG_OVERLAY,
  DEMO_ZIGZAG_CASE_LINK,
  DEMO_ZIGZAG_CASE_LINK_LOGO,
  DEMO_PROOF_CHAPTER,
  DEMO_KEY_LEARNINGS,
  DEMO_KEY_LEARNINGS_SIX,
  DEMO_CTA_CONTACT_PAGE,
} from './demoData';

/**
 * Registr všech sekcí design systému.
 * Každá sekce má id, název, popis a demo props s lorem ipsum.
 */
export const CASE_STUDY_SECTIONS = [
  {
    id: 'intro',
    name: 'Intro',
    description: 'Hero kapitola — logo, stacked media, headline, prose.',
    Component: CaseIntroSection,
    props: DEMO_INTRO,
    stackLayouts: INTRO_STACK_LAYOUTS,
    defaultStackLayout: 'offset',
    supportsHeadlineIndent: true,
  },
  {
    id: 'intro-aside-proofs',
    name: 'Intro + Aside Proofs',
    description: 'Intro s oceněními / proof bloky vpravo od textu.',
    Component: CaseIntroSection,
    props: DEMO_INTRO_ASIDE,
    stackLayouts: INTRO_STACK_LAYOUTS,
    defaultStackLayout: 'offset',
    supportsHeadlineIndent: true,
  },
  {
    id: 'intro-hero-split',
    name: 'Intro Hero Split',
    description: 'Homepage hero — velký nadpis vlevo, subhead + text + CTA vpravo.',
    Component: CaseIntroSection,
    props: DEMO_INTRO_HERO_SPLIT,
    stackLayouts: INTRO_STACK_LAYOUTS,
    defaultStackLayout: 'offset',
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-chapter',
    name: 'Zigzag Chapter',
    description: 'Obsahová kapitola — text vlevo, media vpravo.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-chapter-flip',
    name: 'Zigzag Chapter (Flip)',
    description: 'Zrcadlená varianta — media vlevo, text vpravo.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_FLIP,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-chapter-shift',
    name: 'Zigzag Chapter + Shift',
    description: 'Kapitola s before/after shift blokem pod textem.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_SHIFT,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-body-proofs-stat',
    name: 'Zigzag + Body Proofs (Stat)',
    description: 'Nadpis jedním fontem, stat proof pod textem.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_BODY_PROOFS,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
  },
  {
    id: 'zigzag-body-proofs-awards',
    name: 'Zigzag + Body Proofs (Awards)',
    description: 'Schodový nadpis, ocenění pod textem.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_BODY_AWARDS,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'proof-chapter',
    name: 'Proof Chapter',
    description: 'Důkazová kapitola — delší prose, proof layout.',
    Component: CaseZigzagChapterSection,
    props: DEMO_PROOF_CHAPTER,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-split-prose',
    name: 'Zigzag Split Prose',
    description: 'Manifest system — nadpis vlevo, text + odrážky vpravo, bez médií.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_SPLIT_PROSE,
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-overlay',
    name: 'Zigzag Overlay',
    description: 'Always On — nadpis přes středové médium, logo + text + CTA vpravo.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_OVERLAY,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-case-link',
    name: 'Zigzag Case Link',
    description: 'Case study — text, CTA odkaz a media vpravo.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_CASE_LINK,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'zigzag-case-link-logo',
    name: 'Zigzag Case Link + Logo',
    description: 'Case study — logo klienta nad odstavcem, CTA a media vpravo.',
    Component: CaseZigzagChapterSection,
    props: DEMO_ZIGZAG_CASE_LINK_LOGO,
    stackLayouts: ZIGZAG_STACK_LAYOUTS,
    defaultStackLayout: 'stagger',
    supportsFlip: true,
    supportsHeadlineIndent: true,
  },
  {
    id: 'key-learnings',
    name: 'Key Learnings',
    description: 'Závěrečná sekce se 4 sloupci.',
    Component: CaseKeyLearningsSection,
    props: DEMO_KEY_LEARNINGS,
    supportsHeadlineIndent: true,
  },
  {
    id: 'key-learnings-six',
    name: 'Key Learnings (6)',
    description: 'Závěrečná sekce — 6 sloupců ve 2 řádcích (3×2).',
    Component: CaseKeyLearningsSection,
    props: DEMO_KEY_LEARNINGS_SIX,
    supportsHeadlineIndent: true,
  },
  {
    id: 'cta',
    name: 'CTA',
    description: 'Kontaktní závěr (manifest contact block).',
    Component: CaseCtaSection,
    props: {},
    supportsParallax: true,
  },
  {
    id: 'cta-contact-page',
    name: 'CTA Contact Page',
    description: 'Plná kontaktní sekce — telefon, email, kancelář, fakturace, mapa.',
    Component: CaseCtaSection,
    props: DEMO_CTA_CONTACT_PAGE,
    supportsParallax: true,
  },
];
